language: php
dist: trusty
cache:
  apt: true
matrix:
  include:
  - php: 5.4
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: nightly
  - php: hhvm-3.21
    env: HHVM=true
install:
- if [[ $HHVM == true ]]; then curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar; fi
notifications:
  email: false
after_success:
- bash <(curl -s https://codecov.io/bash)
