language: php

dist: trusty

cache:
  apt: true

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
    - php: hhvm
      env: HHVM=true
  allow_failures:
    - php: hhvm

install:
  - composer install
  - if [[ $HHVM == true ]]; then composer require "phpunit/phpunit:5.7"; fi

script:
  - if [[ $HHVM == true ]]; then ./vendor/bin/phpunit .; fi
  - if [[ $HHVM != true ]]; then phpunit .; fi

notifications:
  email: false

after_success:
- bash <(curl -s https://codecov.io/bash)
